added softwarecheck and permission checks

diff --git a/fastbuild b/fastbuild
--- a/fastbuild
+++ b/fastbuild
@@ -1,8 +1,54 @@
 #!/bin/sh
-apt -qq install dos2unix
+# Check required packages for builds
+DIR=$(pwd)
+set -euo pipefail
+install_if_not_exist() {
+  if dpkg -s "$1" &>/dev/null; then
+    PKG_EXIST=$(dpkg -s "$1" | grep "install ok installed")
+    if [ -z "$PKG_EXIST" ]; then
+      sudo apt install "$1" -y
+    fi
+  else
+    sudo apt install "$1" -y
+  fi
+}
+
+sudo apt update -y
+
+install_if_not_exist git
+install_if_not_exist jq
+install_if_not_exist simple-cdd
+install_if_not_exist dos2unix
+install_if_not_exist libarchive-tools
+install_if_not_exist curl
+install_if_not_exist dosfstools
+install_if_not_exist mtools
+
+##check kali linux debian-cd forked version for bookworm
+##there version has been modified to handle bookworm new firmware pattern
+ver_debian_cd=$(dpkg-query -f '${Version}' -W debian-cd)
+		if dpkg --compare-versions "$ver_debian_cd" lt 3.2.1+kali1; then
+			echo "ERROR: You need debian-cd (>= 3.2.1+kali1), you have $ver_debian_cd" >&2
+                        kali_org="https://http.kali.org/pool/main"
+                        url=$(wget -O- -q --no-check-certificate $kali_org/d/debian-cd | 
+                        sed -ne 's/^.*"\([^"]*debian-cd_[^"]*kali1_all\.deb\)".*/\1/p')
+                        wget $kali_org/d/debian-cd/$url  
+                        # Install the package
+                        sudo dpkg -i $url        
+                        # Clean up
+                        rm "$url"
+fi
+##Deal with Git file permission not staying.
+POSTIN="$DIR/templates/boxtools/DEBIAN/postinst"
+if ! [[ $(stat -c "%A" $POSTIN) =~ "x" ]]; then
+find $DIR/templates -name "postinst" -exec chmod +x {} \;
+fi
+DEH="$DIR/disc-end-hook"
+if ! [[ $(stat -c "%A" $DEH) =~ "x" ]]; then
+ sudo chmod +x "$DEH";
+ fi
 ##make sure linux readable files - caused problems in past
 echo "Making sure all files are Linux readabel"  | wall -n 
-`find $(pwd)/custom_extras/cfg/ -type f -print0 | xargs -0 dos2unix --`
 `find $(pwd)/templates/ -type f -print0 | xargs -0 dos2unix --`
 echo "Starting ISO build with custom install files..!"  | wall -n 
 build-simple-cdd --conf zima.conf --dvd --force-root 
